language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

cache:
  pip: true
  directories:
    - .venv

env:
  global:
    - RANDOM_SEED=0
    - PIPENV_NOSPIN=true
    # Encrypted GH_TOKEN token: http://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci
    - secure: JfVl6zxzhRIEG1VvLqMEPMGOecrzDyb2U0HPyQ4Z4pfKJgFJOdQ1orT9Aztpfr4edXqbCZnEy4WH8+FLBQagkXjT3Ladopv+9j1IkP8v1Gu1O8H2tHQc7wfGxnkQF+h0pFFS6adNAsMliQ5dxTojFYVoWebvZQbiVGYkew+QZ0c=

before_install:
  - pip install pipenv
  - make doctor

install:
  - make install

script:
  - make check
  - make test
  - make demo

after_script: >
  echo $TRAVIS_BRANCH; echo $TRAVIS_PULL_REQUEST; echo $TRAVIS_PYTHON_VERSION;
  if [[ $TRAVIS_BRANCH == 'develop' && $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_PYTHON_VERSION == '3.3' ]]; then

    # Generate Doorstop HTML pages
    make reqs ;

    # Configure Git with Travis CI information
    git config --global user.email "travis@travis-ci.org" ;
    git config --global user.name "travis-ci" ;

    # Delete the current repository
    rm -rf .git ;

    # Rebuild the repository from the generated files and push to GitHub pages
    cd docs/gen ;
    echo "[${TRAVIS_REPO_SLUG}](~${TRAVIS_REPO_SLUG})" | sed -e 's/\//.github.io\//g' | sed -e 's/~/http:\/\//g' > README.md ;
    touch .nojekyll ;
    git init ;
    git add . ;
    git commit -m "Deploy Travis CI build $TRAVIS_BUILD_NUMBER to GitHub pages" ;
    git push -f https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} master:gh-pages ;

  fi

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: change
