site_name: Doorstop
site_description: Requirements management using version control.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/doorstop

theme: readthedocs

pages:
- Home: index.md
- Command-line Interface:
  - Creating Documents: cli/creation.md
  - Reordering Documents: cli/reordering.md
  - Validating Requirements: cli/validation.md
  - Publishing Documents: cli/publishing.md
  - Importing and Exporting: cli/interchange.md
- Graphical Interface: gui/coming-soon.md
- Scripting Interface: api/scripting.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
